### ISSUE TITLE
Evaluate chDB

### ISSUE THREAD

**Issue by wahmedswl** [nshiab/simple-data-analysis#289]
Hi!

Glad to see high performance data analysis in js ecosystem. v2 is based upon DuckDB, did you also evaluated chDB (Embedded ClickHouse) as it seems like more performant than DuckDB.

https://github.com/chdb-io/chdb-node

Thanks

**Comment by nshiab** [comment]
Hi @wahmedswl ! Thanks for the suggestion. From what I can see, chdb-node is still in the early stages. Let me know when you'll have more examples! Good luck with your project! :)
