### ISSUE TITLE
logic/sequence dependency?

### ISSUE THREAD

**Issue by sgilligan** [nshiab/simple-data-analysis#564]
Nice work :)

With the provinces+fire example (tested in Node), if I refactor to create both tables before loading any data, like so

```
    // We create a new table.
    const provinces = sdb.newTable("provinces")
    const fires = sdb.newTable("fires")

    // We fetch the provinces' boundaries. It's a geoJSON.
    await provinces.loadGeoData(
        "https://raw.githubusercontent.com/nshiab/simple-data-analysis/main/test/geodata/files/CanadianProvincesAndTerritories.json"
    )

    // We fetch the wildfires data. It's a CSV.
    await fires.loadData(
        "https://raw.githubusercontent.com/nshiab/simple-data-analysis/main/test/geodata/files/firesCanada2023.csv"
    )
    // We create point geometries from the lat and lon columns
    // and we store the points in the new column geom.
    await fires.points("lat", "lon", "geom")
```

I get 
`
    Error: simple.connection is undefined
`

**Comment by nshiab** [comment]
I am glad you caught that, @sgilligan! This should be fixed now with the latest release:
https://github.com/nshiab/simple-data-analysis/releases/tag/v3.0.13

I'm curious: what are you using simple-data-analysis for? 🤓

**Comment by sgilligan** [comment]
I use duckdb-wasm for tabular data in a web product, and am now interested in the spatial plugin. I thought I'd explore this through your library :)

**Comment by nshiab** [comment]
Cool! :)
