### ISSUE TITLE
Logging decorators

### ISSUE THREAD

**Issue by isabellebouchard** [nshiab/simple-data-analysis#8]
We repeat logging in every single function. Instead, we should create a function that's called as a decorator in `SimpleData` class.

**Comment by nshiab** [comment]
Very good idea. I am currently working on that in the branch overwriteData-option. Pull request to come.

**Comment by nshiab** [comment]
What do you think of something like that @isabellebouchard ?

` clone(options: Options) {
        return methodWrapper(
            "clone",
            this._data,
            [this._defaultOptions],
            clone_,
            { ...this._defaultOptions, ...options }
        )
    }`

with methodWrapper being : 
`
export default function (name: string, incomingData: SimpleDataItem[], parameters: any[], func: Function, options: Options) {
    const start = Date.now()

    options = {
        ...defaultOptions,
        ...options
    }

    options.logs && log("\naddItems()")
    options.logOptions && log("options:")
    options.logOptions && log(options)

    const data = func(incomingData, ...parameters)

    options.logs || options.showDataNoOverwrite && showTable(data, options)

    const end = Date.now()
    options.logs && log(`Done in ${((end - start) / 1000).toFixed(3)} sec.`)

    return options.showDataNoOverwrite ? incomingData : data

}
`

This way, it will stay flexible and we could add as many functionality as we want in it.

**Comment by nshiab** [comment]
Correction: it should be this in the class.

```js
  clone(options: Options) {
        const data = methodWrapper(
            "clone",
            this._data,
            [this._defaultOptions],
            clone_,
            { ...this._defaultOptions, ...options }
        )
        this.#updateSimpleData(data)
        return this
    }
```

**Comment by isabellebouchard** [comment]
Looks great! 

However, I would rather use a more specific name that describes best what the function is doing like `log` instead. 

Also, about the first bit of code, I think it's right, but using this syntax feels more neat to me:
```
@log
 clone(options: Options) {
        return clone_(...)
}
```

**Comment by isabellebouchard** [comment]
If so, we would add a different decorator function to separate concerns.

**Comment by nshiab** [comment]
Ok!
